= Extended Include Macro

Asciidoctor already provides an include macro which can still be used as usual.
However, if the include macro starts with specific variables after the double colon, a special handling of the include macro is activated.
As of now, only one specific variable exists, which is `+++{find}+++` as in `+++include::{find}myFile[]+++`.
Despite having some special handling when using specific variables, the usual behaviour of the built-in include is still preserved and all its attributes can still be used.
The following documentation focuses on the include macro with activated special handling.

[.language-asciidoc]
== `+++{find}+++` Include Macro

The general idea of the `+++{find}+++` variable in an include macro is to search the given file and replace the variable with the path to the matched file.
In short, it behaves the same like the `+++{find}+++` variable (see: <<special-variables.adoc#find,Special Variables - Find>>), but enables two additional attributes which can be given in the squared brackets of the include macro.


Usage: ::
[.language-asciidoc]``+++include::{find}Target[Attributes]+++``


With: ::
* *Target* (required):
	The name of the file whose contents shall be included.
	The file name can contain directories.
	The extension `.adoc` can be omitted.


* *Attributes* (optional):
** *FILE_ONCE*: Includes the same file only once.
** *TARGET_ONCE* (alias *ONCE*): Includes the same target only once.
** (all other include attributes such as 'lines')



Warnings and Errors: ::
* *Error: File Not Found*
	Is issued in case the given target could not be found.

* *Error: Circular Dependency*
	Is issued in case the included files depend on each other.
	The last file which would create a circular dependency cycle is omitted.
	This error is only issued if all include macros of the cycle use the `+++{find}+++` macro.

* *Warning: Cant Find Circular Dependencies*
	Is issued in case one or more includes do not use the `+++{find}+++` macro.
	Despite this issue, circular dependencies can still be found if all of the causing files are included using the `+++{find}+++` macro.

* *Warning: Multiple File Matches*
	Is issued in case the given target is found at multiple locations.
	The first match is chosen to be included.

* *Warning: Inconsistent Use of Attributes*
	Is issued in case one of the attributes is used inconsistently.
	The TARGET_ONCE attribute is supposed to be used at none or at all includes with the same target.
	The FILE_ONCE attribute is supposed to be used at none or at all includes matching the same file.




Example: ::

The following line includes the file `file.adoc` in the subdir `dir`.
The location of that file is found by the `+++{find}+++` directive (see: <<special-variables>>).
The attribute `ONCE` is the shorthand form for `TARGET_ONCE`.


[.language-asciidoc]``+++include::{find}dir/file.adoc[ONCE]+++``



== `+++{api}+++` Include Macro

Includes generated adoc (of StdLib API) text which previously was generated by the exporter wizard.
Uses a PQN to reference the section which is to be included.
(tbd)

== `+++{src}+++` Include Macro

Includes source code (of StdLib API) from GitHub.
Uses a PQN to reference the source element (e.g. a method) which is to be included.
(tbd)
