= Inline Cwiki Macro

Usage::
[source,asciidoc]
cwiki:target[title="cwikiTitle"]

The Inline Cwiki Macro creates hyperlinks to Confluence wiki entries.
The string 'title=' and the quotation marks are optional.


Attributes::
* *target:* Used to define which Confluence URL to link to. Can be one of the following:
. pageID (e.g. `56885484`).
. path (e.g. `BR/Continuous+Integration`).
* *cwikiTitle:* (optional) The title that will be displayed as an anchor in the generated hyperlink.
If no title is declared, the `target` will be used instead.

[.language-asciidoc]
== URL Pattern

With most Confluence pages, the *URL path* is derived from the page title, like so:

`confluence.numberfour.eu/display/N4/Continuous+Integration`

Not all Confluence pages have associated paths and will otherwise have a *page ID* as with the following:


`confluence.numberfour.eu/pages/viewpage.action?pageId=56885484`

A target that contains only numbers (e.g., `+++cwiki:1234[]+++`) will be interpreted as a page ID rather than a page path.
To configure the Inline Cwiki Macro to resolve to correct targets, the format of the URL pattern should be set in the **https://github.numberfour.eu/NumberFour/asciispec/blob/master/docs/examples/config.adoc[Configuration File]** as follows:

[source,asciidoc]
----
:cwiki_def: <Path-URL-Pattern>;<ID-URL-Pattern>;<Icon>;<Title-Pattern>
----

<Path-URL-Pattern> :: Used to generate the target URL when a path is specified - can contain the placeholder `+++{PATH}+++`.
<ID-URL-Pattern> :: Used to generate the link target URL when a page ID is specified - can contain the placeholder `+++{PAGE_ID}+++`.
<Icon> :: A path to an icon, e.g., `images/icons/confluence.png`.
<Title-Pattern> :: the pattern used to generate the link's text - can contain the placeholder `+++{TITLE}+++`.

Examples::

// tag::inline.cwiki.example[]

ifndef::env-github[]

[example]
Documented at **+++cwiki:BR/Continuous+Integration[title=Continuous Integration]+++**...

Documented at cwiki:BR/Continuous+Integration[title=Continuous Integration]...

[example]
See the **+++cwiki:56885484["MacOS Devices wiki entry"]+++** to connect to...

See the cwiki:56885484["MacOS Devices wiki entry"] to connect to...

endif::[]

ifdef::env-github[]

[example]
Documented at **+++cwiki:BR/Continuous+Integration[title=Continuous Integration]+++** ...

Documented at https://confluence.numberfour.eu/display/BR/Continuous+Integration[Continuous Integration]...

[example]
See the **+++cwiki:56885484["MacOS Devices wiki entry"]+++** to connect to...

See the https://confluence.numberfour.eu/pages/viewpage.action?pageId=56885484[MacOS Devices wiki entry] to connect to...

endif::[]

