ifdef::env-github,env-browser[:outfilesuffix: .adoc]

       _             _ _ ____
      / \   ___  ___(_|_) ___| _ __   ___  ___
     / _ \ / __|/ __| | \___ \| '_ \ / _ \/ __|
    / ___ \\__ \ (__| | |___) | |_) |  __/ (__
   /_/   \_\___/\___|_|_|____/| .__/ \___|\___|
                              |_|

A documentation toolchain based on http://asciidoctor.org/[AsciiDoctor]. It implements custom processors for technical writing, organizing documentation and task management.

== Features
*<<docs/custom-processors/extended-include-macro#,include::{}[ ] - Include (extended)>>*: Includes files using special variables. +
*<<docs/custom-processors/inline-task-macro#,task:[ ] - Inline Task>>*: Insert links to Jira and GitHub. +
*<<docs/custom-processors/inline-cwiki-macro#,cwiki:[ ] - Inline Cwiki>>*: Inserting links to Confluence Wiki pages. +
*<<docs/custom-processors/definition-block#,[def] - Definition Block>>*: Add definitions with custom formatting. +
*<<docs/custom-processors/requirements-block#,[req] - Requirement Block>>*: Add requirements with custom formatting. +
*<<docs/custom-processors/inline-bibtex-macro#,cite:[ ] - Inline BibTeX>>*: Inserting citations from a BibTeX file. +
*<<docs/custom-processors/inline-srclnk-macro#,srclnk:[ ] - Inline Source Link>>*: Inserting links to source files on GitHub. +
*<<docs/custom-processors/inline-math-macro#,math:[ ] - Inline Math>>*: Inserting math expressions. +
*<<docs/custom-processors/math-block#,[math] - Math Block>>*: Add long math formulae. +



==  Prerequisites

* http://maven.apache.org/[Apache Maven]
* https://github.com/asciidoctor/asciidoctorj/tree/asciidoctorj-1.6.0[asciidoctorj-1.6.0]. There is no artifact publicly available at the moment. Please follow these steps:
.. Checkout https://github.com/asciidoctor/asciidoctorj/tree/asciidoctorj-1.6.0[asciidoctorj-1.6.0]
.. Navigate to the root of the asciidoctorj-1.6.0 project and run `./gradlew assemble`
.. Install the dependency to your local maven repository by running

== Build


To build the project, clone this repository, navigate to the project folder and run the following command:

[source,bash]
mvn clean package

After maven has successfully finished building the project, a zip file containing the asciispec tool is available under `asciispec/target/asciispec-bin.zip`

[.language-bash]
== Installation
Add AsciiSpec to your shell profile with the path to the `asciispec/bin` directory on your system:

`pass:[export PATH=$PATH:~/path/to/asciispec/bin/]`

If the AsciiSpec tool is found by your system, running AsciiSpec with the `-h` flag will print a help page:

[source,bash]
asciispec -h

== Usage
=== Convert to HTML
Generates a `sample.html` file in the current directory:

[source,bash]
asciispec sample.adoc

=== Convert to DocBook:
Generates a `sample.xml` file in the current directory.

[source,bash]
asciispec -b docbook sample.adoc

DocBook format can be further converter to *PDF* with https://github.com/NumberFour/asciidoctor-fopub[asciidoctor-fopub]. This fork of the fopub project contains some cosmetic changes.

=== Help
Running `asciispec -h` will print the AsciiDoctor help page. +
For more options, see the http://asciidoctor.org/docs/user-manual/#cli-options[CLI Options] section of the AsciiDoctor user manual.

== Documentation

[horizontal]
GitHub pages:: *http://numberfour.github.io/asciispec*
Userguide:: *<<docs/userguide#,Userguide>>*: Common, practical AsciiDoc syntax and AsciiSpec-specific tips.
Docs Index:: *<<docs/index#,AsciiSpec Specification>>*: Full AsciiSpec documentation.
Other:: *<<docs/troubleshooting#,Troubleshooting>>*: Common tips for getting started and debugging errors.
